apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: LoadBalancer
  ports:
    - port: 1025
      name: smtp
    - port: 1143
      name: imap
  selector:
    instance: {{ .Release.Name }}