apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  # serviceName: {{ .Release.Name }}-postgres-service
  replicas: 1
  selector:
    matchLabels:
      instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        instance: {{ .Release.Name }}
    spec:
      containers:
      - name: protonmailbridge
        image: shenxn/protonmail-bridge:latest
        # set the pgdata to /pgdata
        # ports:
        # - containerPort: 5432
        #   name: postgres
        volumeMounts:
        - name: bridgedata
          mountPath: /root
  volumeClaimTemplates:
  - metadata:
      name: bridgedata
    spec:
      storageClassName: longhorn
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi